In [1]:
pip install flask

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib as plt
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

df=pd.read_csv('D:/UWE/MachineLearning/Week4/Tutorial/breast-cancer-wisconsin.data.txt')
df

id  par1  par2  par3  par4  par5 par6  par7  par8  par9  class
0    1000025     5     1     1     1     2    1     3     1     1      2
1    1002945     5     4     4     5     7   10     3     2     1      2
2    1015425     3     1     1     1     2    2     3     1     1      2
3    1016277     6     8     8     1     3    4     3     7     1      2
4    1017023     4     1     1     3     2    1     3     1     1      2
..       ...   ...   ...   ...   ...   ...  ...   ...   ...   ...    ...
694   776715     3     1     1     1     3    2     1     1     1      2
695   841769     2     1     1     1     2    1     1     1     1      2
696   888820     5    10    10     3     7    3     8    10     2      4
697   897471     4     8     6     4     3    4    10     6     1      4
698   897471     4     8     8     5     4    5    10     4     1      4

[699 rows x 11 columns]

In [3]:
df.describe

df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      699 non-null    int64 
 1   par1    699 non-null    int64 
 2   par2    699 non-null    int64 
 3   par3    699 non-null    int64 
 4   par4    699 non-null    int64 
 5   par5    699 non-null    int64 
 6   par6    699 non-null    object
 7   par7    699 non-null    int64 
 8   par8    699 non-null    int64 
 9   par9    699 non-null    int64 
 10  class   699 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.2+ KB


In [4]:
#remove outliers and noicey value s
df.replace('?',-99999,inplace=True)
df.drop(['id'],1,inplace=True)#1 means column


C:\Users\user\AppData\Local\Temp\ipykernel_5044\662360101.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df.drop(['id'],1,inplace=True)#1 means column


In [5]:
df

par1  par2  par3  par4  par5 par6  par7  par8  par9  class
0       5     1     1     1     2    1     3     1     1      2
1       5     4     4     5     7   10     3     2     1      2
2       3     1     1     1     2    2     3     1     1      2
3       6     8     8     1     3    4     3     7     1      2
4       4     1     1     3     2    1     3     1     1      2
..    ...   ...   ...   ...   ...  ...   ...   ...   ...    ...
694     3     1     1     1     3    2     1     1     1      2
695     2     1     1     1     2    1     1     1     1      2
696     5    10    10     3     7    3     8    10     2      4
697     4     8     6     4     3    4    10     6     1      4
698     4     8     8     5     4    5    10     4     1      4

[699 rows x 10 columns]

In [6]:
x=df.iloc[:,0:9]

In [7]:
X=np.array(df.iloc[:,0:9])
X

array([[5, 1, 1, ..., 3, 1, 1],
       [5, 4, 4, ..., 3, 2, 1],
       [3, 1, 1, ..., 3, 1, 1],
       ...,
       [5, 10, 10, ..., 8, 10, 2],
       [4, 8, 6, ..., 10, 6, 1],
       [4, 8, 8, ..., 10, 4, 1]], dtype=object)

In [8]:
Y=np.array(df.iloc[:,-1])
Y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 4,
       4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
       2, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4,

In [9]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,random_state=0)

In [10]:
clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train,Y_train)
print(clf.score(X_train,Y_train))
print(clf.score(X_test,Y_test))


0.9751908396946565
0.9828571428571429


In [11]:
#usign confution matrix

In [12]:
y_predict=clf.predict(X_test)


In [13]:

cm=confusion_matrix(Y_test,y_predict)
ac=accuracy_score(Y_test,y_predict)
print(cm)
print(ac)

[[111   1]
 [  2  61]]
0.9828571428571429


In [14]:
userDataSet=np.array([4,3,3,4,1,2,3,5,2])
userDataSet=userDataSet.reshape(1,-1)
userDataSet
#predictions=clf.predict(userDataSet)

array([[4, 3, 3, 4, 1, 2, 3, 5, 2]])

In [15]:
#userDataSet=np.array([4,3,3,4,1,2,3,5,2])
predictions=clf.predict(userDataSet)
print(predictions)

[2]


In [16]:
#without dropped id

In [17]:
df2=pd.read_csv('D:/UWE/MachineLearning/Week4/Tutorial/breast-cancer-wisconsin.data.txt')
df2

id  par1  par2  par3  par4  par5 par6  par7  par8  par9  class
0    1000025     5     1     1     1     2    1     3     1     1      2
1    1002945     5     4     4     5     7   10     3     2     1      2
2    1015425     3     1     1     1     2    2     3     1     1      2
3    1016277     6     8     8     1     3    4     3     7     1      2
4    1017023     4     1     1     3     2    1     3     1     1      2
..       ...   ...   ...   ...   ...   ...  ...   ...   ...   ...    ...
694   776715     3     1     1     1     3    2     1     1     1      2
695   841769     2     1     1     1     2    1     1     1     1      2
696   888820     5    10    10     3     7    3     8    10     2      4
697   897471     4     8     6     4     3    4    10     6     1      4
698   897471     4     8     8     5     4    5    10     4     1      4

[699 rows x 11 columns]

In [18]:
df2.replace('?',-99999,inplace=True)

In [19]:
X=np.array(df2.iloc[:,0:9])
X


array([[1000025, 5, 1, ..., '1', 3, 1],
       [1002945, 5, 4, ..., '10', 3, 2],
       [1015425, 3, 1, ..., '2', 3, 1],
       ...,
       [888820, 5, 10, ..., '3', 8, 10],
       [897471, 4, 8, ..., '4', 10, 6],
       [897471, 4, 8, ..., '5', 10, 4]], dtype=object)

In [20]:
y=df2.iloc[:,-1]
y=np.array(y)
y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 4,
       4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
       2, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4,

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [22]:
clf=KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train,y_train)
print(clf.score(X_train,y_train))
print(clf.score(X_test,y_test))


0.7423664122137404
0.64


In [23]:
#using Other distance matrixes

In [24]:
df3=pd.read_csv('D:/UWE/MachineLearning/Week4/Tutorial/breast-cancer-wisconsin.data.txt')
df3

id  par1  par2  par3  par4  par5 par6  par7  par8  par9  class
0    1000025     5     1     1     1     2    1     3     1     1      2
1    1002945     5     4     4     5     7   10     3     2     1      2
2    1015425     3     1     1     1     2    2     3     1     1      2
3    1016277     6     8     8     1     3    4     3     7     1      2
4    1017023     4     1     1     3     2    1     3     1     1      2
..       ...   ...   ...   ...   ...   ...  ...   ...   ...   ...    ...
694   776715     3     1     1     1     3    2     1     1     1      2
695   841769     2     1     1     1     2    1     1     1     1      2
696   888820     5    10    10     3     7    3     8    10     2      4
697   897471     4     8     6     4     3    4    10     6     1      4
698   897471     4     8     8     5     4    5    10     4     1      4

[699 rows x 11 columns]

In [25]:
df3.drop(['id'],1,inplace=True)
df3

C:\Users\user\AppData\Local\Temp\ipykernel_5044\2270815996.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  df3.drop(['id'],1,inplace=True)


par1  par2  par3  par4  par5 par6  par7  par8  par9  class
0       5     1     1     1     2    1     3     1     1      2
1       5     4     4     5     7   10     3     2     1      2
2       3     1     1     1     2    2     3     1     1      2
3       6     8     8     1     3    4     3     7     1      2
4       4     1     1     3     2    1     3     1     1      2
..    ...   ...   ...   ...   ...  ...   ...   ...   ...    ...
694     3     1     1     1     3    2     1     1     1      2
695     2     1     1     1     2    1     1     1     1      2
696     5    10    10     3     7    3     8    10     2      4
697     4     8     6     4     3    4    10     6     1      4
698     4     8     8     5     4    5    10     4     1      4

[699 rows x 10 columns]

In [26]:
df3.replace('?',-99999,inplace=True)

In [27]:
X=df3.iloc[:,0:9]
X=np.array(X)
X[[1]]

array([[5, 4, 4, 5, 7, '10', 3, 2, 1]], dtype=object)

In [28]:
y=df3.iloc[:,-1]
y=np.array(y)
y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 4, 4, 4,
       4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4,
       2, 4, 4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4,
       2, 4, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2,
       4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2,
       2, 4, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4,
       2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2,
       2, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4,
       4, 2, 4, 4, 2, 2, 4, 4, 2, 4, 2, 2, 2, 4, 4,

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)


In [30]:
clf=KNeighborsClassifier(n_neighbors=5,metric='manhattan')
clf.fit(X_train,y_train)
print(clf.score(X_train,y_train))
print(clf.score(X_test,y_test))


0.9732824427480916
0.9771428571428571


In [31]:
X_test

array([[4, 1, 2, ..., 1, 1, 1],
       [4, 2, 2, ..., 2, 1, 1],
       [6, 6, 6, ..., 7, 8, 1],
       ...,
       [5, 3, 2, ..., 1, 1, 1],
       [1, 1, 1, ..., 3, 1, 1],
       [4, 1, 1, ..., 3, 2, 1]], dtype=object)

In [32]:
y_predict=clf.predict(X_test)
y_predict

array([2, 2, 2, 2, 4, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 4, 4,
       2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2,
       4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4,
       4, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2,
       4, 4, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2,
       4, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2,
       2, 4, 4, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       2, 2, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2],
      dtype=int64)

In [33]:
y_test_predit=clf.predict([[5, 4, 4, 5, 7, 10, 3, 2, 1],[1,1, 1, 5, 7, 4, 3, 10, 1]])
y_test_predit

array([4, 2], dtype=int64)

In [34]:
cm=confusion_matrix(y_test,y_predict)
ac=accuracy_score(y_test,y_predict)
print(cm)
print(ac)

[[111   1]
 [  3  60]]
0.9771428571428571


In [35]:
clf=KNeighborsClassifier(n_neighbors=5,metric='minkowski')
clf.fit(X_train,y_train)
print(clf.score(X_train,y_train))
print(clf.score(X_test,y_test))


0.9751908396946565
0.9828571428571429


In [36]:
y_predict=clf.predict(X_test)

In [37]:
cm=confusion_matrix(y_test,y_predict)
ac=accuracy_score(y_test,y_predict)
print(cm)
print(ac)

[[111   1]
 [  2  61]]
0.9828571428571429


# Expouse model

In [38]:
import joblib
joblib.dump(clf, 'model.pkl')
print("Model dumped!")

# Load the model that you just saved
clf = joblib.load('model.pkl')

# Saving the data columns from training
model_columns = list(x.columns)
joblib.dump(model_columns, 'model_columns.pkl')

Model dumped!


['model_columns.pkl']

In [ ]:
from flask import Flask, request, jsonify
import joblib
import traceback
import pandas as pd
import numpy as np

# Your API definition
app = Flask(__name__)

@app.route('/predictModel', methods=['POST'])
def predict():
    if clf:
        try:
            json_ = request.json
            print(json_)
            query = pd.DataFrame(json_)
            #query = query.reindex(columns=model_columns, fill_value=0)

            prediction = list(clf.predict(query))

            return jsonify({'prediction': str(prediction)})

        except:

            return jsonify({'trace': traceback.format_exc()})
    else:
        print ('Train the model first')
        return ('No model here to use')

if __name__ == '__main__':
    
    clf = joblib.load("model.pkl") # Load "model.pkl"
    print ('Model loaded')
    model_columns = joblib.load("model_columns.pkl") # Load "model_columns.pkl"
    print ('Model columns loaded')

    app.run(debug=True,port=23232,use_reloader=False)

Model loaded
Model columns loaded
 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:23232
Press CTRL+C to quit
127.0.0.1 - - [21/Feb/2024 07:45:29] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [21/Feb/2024 07:45:31] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [21/Feb/2024 07:46:56] "GET /predict HTTP/1.1" 404 -
127.0.0.1 - - [21/Feb/2024 07:49:34] "POST /predictModel HTTP/1.1" 200 -
127.0.0.1 - - [21/Feb/2024 07:49:39] "POST /predictModel HTTP/1.1" 200 -


[[5, 4, 4, 5, 7, 10, 3, 2, 1], [1, 1, 1, 5, 7, 4, 3, 10, 1]]
